name: build-and-push
on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/superplural/superplural-omni
  DOCKERFILE_PATH: docker/dockerfiles/ 
  CONTEXT_PATH: .                                      # ajuste se seu Dockerfile exigir outro contexto

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_PATH }}
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
